title: "Valentin Vanelslande's Website"
minimal_mistakes_skin: default

markdown: kramdown
remote_theme: mmistakes/minimal-mistakes

include:
  - _pages

plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-include-cache
  - jekyll-redirect-from

footer:
  links:
    - label: GitHub
      icon: fab fa-fw fa-github
      url: https://github.com/vvanelslande
    - label: Twitter
      icon: fab fa-fw fa-twitter
      url: https://twitter.com/valentinvvctre
    - label: Website License (GPLv3)
      icon: fas fa-fw fa-file-alt
      url: https://vvanelslande.github.io/license.txt

defaults:
  - scope:
      path: ""
      type: pages
    values:
      layout: single
      sidebar:
        nav: sidebar
